export const ROUTEID_TO_STOPS = {
  777: {
    route_id: 777,
    route_long_name: "1636'er",
    route_color: '#0099FF',
    stops: [
      { stop_number: 1, stop_name: 'Quad' },
      { stop_number: 2, stop_name: 'Radcliffe Yard' },
      { stop_number: 3, stop_name: 'Mass and Garden' },
      { stop_number: 4, stop_name: 'Law School (WCC)' },
      { stop_number: 5, stop_name: 'Maxwell Dworkin' },
      { stop_number: 6, stop_name: 'Science Center' },
      { stop_number: 7, stop_name: 'Memorial Hall' },
      { stop_number: 8, stop_name: 'Lamont Library' },
      { stop_number: 9, stop_name: 'Leverett House' },
      { stop_number: 10, stop_name: 'Mather House' },
      { stop_number: 11, stop_name: 'The Inn' },
      { stop_number: 12, stop_name: 'Widener Gate' },
      { stop_number: 13, stop_name: 'Cambridge Common' },
    ],
  },
  778: {
    route_id: 778,
    route_long_name: 'Allston Loop',
    route_color: '#A50606',
    stops: [
      { stop_number: 1, stop_name: 'SEC' },
      { stop_number: 2, stop_name: "Barry's Corner (Northbound)" },
      { stop_number: 3, stop_name: 'Stadium (Northbound)' },
      { stop_number: 4, stop_name: 'Kennedy School (Northbound)' },
      { stop_number: 5, stop_name: 'Harvard Square (Northbound)' },
      { stop_number: 6, stop_name: 'Law School (WCC)' },
      { stop_number: 7, stop_name: 'Maxwell Dworkin' },
      { stop_number: 8, stop_name: 'Science Center' },
      { stop_number: 9, stop_name: 'Memorial Hall' },
      { stop_number: 10, stop_name: 'Lamont Library' },
      { stop_number: 11, stop_name: 'Leverett House' },
      { stop_number: 12, stop_name: '1 Western Ave' },
      { stop_number: 13, stop_name: 'SEC' },
    ],
  },
  783: {
    route_id: 783,
    route_long_name: 'Crimson Cruiser',
    route_color: '#DB0DD7',
    stops: [
      { stop_number: 1, stop_name: 'Mather House' },
      { stop_number: 2, stop_name: 'The Inn' },
      { stop_number: 3, stop_name: 'Widener Gate' },
      { stop_number: 4, stop_name: 'Quad' },
      { stop_number: 5, stop_name: 'Radcliffe Yard' },
      { stop_number: 6, stop_name: 'Mass and Garden' },
      { stop_number: 7, stop_name: 'Law School (WCC)' },
      { stop_number: 8, stop_name: 'Maxwell Dworkin' },
      { stop_number: 9, stop_name: 'Science Center' },
      { stop_number: 10, stop_name: 'Memorial Hall' },
      { stop_number: 11, stop_name: 'Lamont Library' },
      { stop_number: 12, stop_name: 'Leverett House' },
    ],
  },
  2021: {
    route_id: 2021,
    route_long_name: 'HUIT Route',
    route_color: '#F4EC07',
    stops: [
      { stop_number: 1, stop_name: 'Widener Gate' },
      { stop_number: 2, stop_name: '784 Memorial Drive' },
    ],
  },
  789: {
    route_id: 789,
    route_long_name: 'Mather Express',
    route_color: '#0000FF',
    stops: [
      { stop_number: 1, stop_name: 'Mather House' },
      { stop_number: 2, stop_name: 'The Inn' },
      { stop_number: 3, stop_name: 'Widener Gate' },
      { stop_number: 4, stop_name: 'Maxwell Dworkin' },
      { stop_number: 5, stop_name: 'Science Center' },
      { stop_number: 6, stop_name: 'Memorial Hall' },
      { stop_number: 7, stop_name: 'Lamont Library' },
      { stop_number: 8, stop_name: 'Leverett House' },
    ],
  },
  785: {
    route_id: 785,
    route_long_name: 'Overnight',
    route_color: '#FF8707',
    stops: [
      { stop_number: 1, stop_name: 'Mather House' },
      { stop_number: 2, stop_name: 'The Inn' },
      { stop_number: 3, stop_name: 'Widener Gate' },
      { stop_number: 4, stop_name: 'Quad' },
      { stop_number: 5, stop_name: 'Radcliffe Yard' },
      { stop_number: 6, stop_name: 'Mass and Garden' },
      { stop_number: 7, stop_name: 'Law School (WCC)' },
      { stop_number: 8, stop_name: 'Maxwell Dworkin' },
      { stop_number: 9, stop_name: 'Science Center' },
      { stop_number: 10, stop_name: 'Memorial Hall' },
      { stop_number: 11, stop_name: 'Lamont Library' },
      { stop_number: 12, stop_name: 'Winthrop House' },
      { stop_number: 13, stop_name: 'Leverett House' },
    ],
  },
  790: {
    route_id: 790,
    route_long_name: 'Quad Express',
    route_color: '#136D1C',
    stops: [
      { stop_number: 1, stop_name: 'Quad' },
      { stop_number: 2, stop_name: 'Radcliffe Yard' },
      { stop_number: 3, stop_name: 'Mass and Garden' },
      { stop_number: 4, stop_name: 'Law School (WCC)' },
      { stop_number: 5, stop_name: 'Maxwell Dworkin' },
      { stop_number: 6, stop_name: 'Science Center' },
      { stop_number: 7, stop_name: 'Memorial Hall' },
      { stop_number: 8, stop_name: 'Quad' },
    ],
  },
  2235: {
    route_id: 2235,
    route_long_name: 'Quad SEC Direct',
    route_color: '#9467BD',
    stops: [
      { stop_number: 1, stop_name: 'SEC' },
      { stop_number: 2, stop_name: "Barry's Corner (Northbound)" },
      { stop_number: 3, stop_name: 'Stadium (Northbound)' },
      { stop_number: 4, stop_name: 'Kennedy School (Northbound)' },
      { stop_number: 5, stop_name: 'Harvard Square (Northbound)' },
      { stop_number: 6, stop_name: 'Law School (WCC)' },
      { stop_number: 7, stop_name: 'Quad' },
      { stop_number: 8, stop_name: 'Radcliffe Yard' },
      { stop_number: 9, stop_name: 'Mass and Garden' },
      { stop_number: 10, stop_name: 'Harvard Square (Southbound)' },
      { stop_number: 11, stop_name: 'Kennedy School (Southbound)' },
      { stop_number: 12, stop_name: 'Stadium (Southbound)' },
      { stop_number: 13, stop_name: "Barry's Corner (Southbound)" },
      { stop_number: 14, stop_name: 'SEC' },
    ],
  },
  792: {
    route_id: 792,
    route_long_name: 'Quad Stadium Express',
    route_color: '#50BC48',
    stops: [
      { stop_number: 1, stop_name: 'Quad' },
      { stop_number: 2, stop_name: 'Radcliffe Yard' },
      { stop_number: 3, stop_name: 'Mass and Garden' },
      { stop_number: 4, stop_name: 'Lamont Library' },
      { stop_number: 5, stop_name: 'Winthrop House' },
      { stop_number: 6, stop_name: 'Leverett House' },
      { stop_number: 7, stop_name: 'Mather House' },
      { stop_number: 8, stop_name: 'Stadium (Northbound)' },
      { stop_number: 9, stop_name: 'Kennedy School (Northbound)' },
      { stop_number: 10, stop_name: 'Harvard Square (Northbound)' },
    ],
  },
  793: {
    route_id: 793,
    route_long_name: 'Quad Yard Express',
    route_color: '#006600',
    stops: [
      { stop_number: 1, stop_name: 'Quad' },
      { stop_number: 2, stop_name: 'Radcliffe Yard' },
      { stop_number: 3, stop_name: 'Mass and Garden' },
      { stop_number: 4, stop_name: 'Lamont Library' },
      { stop_number: 5, stop_name: 'Widener Gate' },
      { stop_number: 6, stop_name: 'Cambridge Common' }],
  },
}
